apiVersion: apps/v1
kind: Deployment
metadata:
  name: annuaire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annuaire
  template:
    metadata:
      labels:
        app: annuaire
    spec:
      containers:
        - name: annuaire
          image: mailinenguyen/annuaire
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-annuaire-postgresql
                  key: postgres-password
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-annuaire-postgresql/